# Generated by Django 6.0.4 on 2026-04-09 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('FIZ', 'Фізичне лице'), ('FOP', 'ФОП'), ('COMP', 'Компанія')], max_length=10, verbose_name='Тип клієнта')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name="Ім'я")),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Прізвище')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Номер телефону')),
                ('email', models.EmailField(blank=True, max_length=127, null=True, verbose_name='Електронна пошта')),
                ('ipn', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Ідентифікаційний код')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва компанії')),
                ('edrpou', models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='ЄДРПОУ')),
                ('created', models.DateField(auto_now=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Клієнт',
                'verbose_name_plural': 'Клієнти',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name="Ім'я")),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Прізвище')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='Номер телефону')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Фото')),
                ('license', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Посвідчення водія')),
                ('ipn', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Ідентифікаційний код')),
                ('about', models.TextField(max_length=500, null=True, verbose_name='Досвід роботи. Про себе')),
                ('status', models.CharField(choices=[('F', 'Вільний'), ('OW', 'В дорозі'), ('W', 'Вихідний')], default='F', max_length=20, verbose_name='Статус')),
                ('weekend_until', models.DateField(blank=True, null=True, verbose_name='Вихідний до')),
            ],
            options={
                'verbose_name': 'Водій',
                'verbose_name_plural': 'Водії',
                'ordering': ('last_name',),
            },
        ),
        migrations.CreateModel(
            name='NoPayedOrder',
            fields=[
                ('pay_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Айді оплати')),
                ('date', models.CharField(blank=True, null=True, verbose_name='Дата')),
                ('company', models.CharField(blank=True, null=True, verbose_name='Компанія')),
                ('name', models.CharField(blank=True, null=True, verbose_name='ПІБ/Представник')),
                ('ipn', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ідентифікаційни код')),
                ('edrpou', models.CharField(blank=True, max_length=8, null=True, verbose_name='ЄДРПОУ')),
                ('total', models.IntegerField(blank=True, default=0, null=True, verbose_name='Сума')),
            ],
            options={
                'verbose_name': 'Не оплачене замовлення',
                'verbose_name_plural': 'Не оплачені замовлення',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_model', models.CharField(blank=True, max_length=40, null=True, verbose_name='Модель')),
                ('license_plate', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номера')),
                ('fuel_rate', models.IntegerField(blank=True, default=0, verbose_name='Рівень палива')),
                ('vin', models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='VIN-номер')),
                ('mileage', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Пробіг')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Фото')),
                ('status', models.CharField(choices=[('F', 'Вільний'), ('OW', 'В дорозі')], default='F', max_length=20, verbose_name='Статус')),
                ('to', models.CharField(choices=[('NS', 'Потрібне ТО'), ('S', 'Обслужений'), ('OS', 'На обслуговувані'), ('R', 'В ремонті')], default='S', max_length=20, verbose_name='Технічне обслуговування')),
                ('miles_to_inspect', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='ТО раз в')),
                ('next_inspect', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Наступне ТО')),
            ],
            options={
                'verbose_name': 'Транспорт',
                'verbose_name_plural': 'Транспорти',
                'ordering': ('transport_model',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Айді оплати')),
                ('order_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва замовлення')),
                ('price', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Ціна')),
                ('status', models.CharField(blank=True, choices=[('W', 'Очікує'), ('D', 'Доставляється'), ('E', 'Доставлено')], default='W', null=True, verbose_name='Статус доставки')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Адреса доставки')),
                ('payment_status', models.CharField(blank=True, choices=[('NP', 'Не оплачено'), ('P', 'Оплачено')], default='NP', max_length=40, null=True, verbose_name='Статус оплати')),
                ('date', models.DateField(auto_now=True, null=True, verbose_name='Дата створення')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ('client_id',),
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('S', 'ТО'), ('R', 'Ремонт'), ('E', 'Завершено')], max_length=15, verbose_name='Тип обслуговування')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Ціна')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('transport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.transport')),
            ],
            options={
                'verbose_name': 'Технічне обслуговування',
                'verbose_name_plural': 'Технічні обслуговування',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.CharField(blank=True, max_length=100, null=True, verbose_name='Старт')),
                ('end_point', models.CharField(blank=True, max_length=100, null=True, verbose_name='Кінець')),
                ('status', models.CharField(choices=[('AC', 'Очікує підтвердження'), ('P', 'Виконується'), ('C', 'Виконано')], default='AC', max_length=20, verbose_name='Статус')),
                ('distance', models.IntegerField(blank=True, default=0, null=True, verbose_name='Відстань')),
                ('fuel_status', models.CharField(choices=[('O', 'Надвитрата'), ('N', 'Норма')], default='N', max_length=20, verbose_name='Статус пального')),
                ('fuel_actual', models.IntegerField(blank=True, default=0, null=True, verbose_name="Реальний об'єм палива")),
                ('fuel_planned', models.IntegerField(blank=True, default=0, null=True, verbose_name="Запланований об'єм палива")),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.driver')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order')),
                ('transport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.transport')),
            ],
            options={
                'verbose_name': 'Поїздка',
                'verbose_name_plural': 'Поїздки',
            },
        ),
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liters', models.IntegerField(blank=True, default=0, null=True, verbose_name='Літри')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Ціна')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата заправки')),
                ('transport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.transport')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.trip')),
            ],
            options={
                'verbose_name': 'Паливо',
                'verbose_name_plural': 'Палива',
            },
        ),
    ]
