# Generated by Django 5.2.8 on 2025-11-30 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('license', models.CharField(max_length=100)),
                ('experience', models.TextField(max_length=500)),
                ('phone', models.CharField(max_length=13)),
            ],
            options={
                'verbose_name': 'Водій',
                'verbose_name_plural': 'Водії',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('transport_model', models.CharField(max_length=40)),
                ('license_plate', models.CharField(max_length=8)),
                ('fuel_rate', models.SmallIntegerField(max_length=8)),
                ('vin', models.CharField(max_length=17)),
                ('mileage', models.SmallIntegerField(max_length=10)),
                ('status', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Транспорт',
                'verbose_name_plural': 'Транспорти',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=15)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('transport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.transport')),
            ],
            options={
                'verbose_name': 'Технічне обслуговування',
                'verbose_name_plural': 'Технічні обслуговування',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_point', models.CharField(max_length=20)),
                ('end_point', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=15)),
                ('distance', models.IntegerField(max_length=5)),
                ('fuel_planned', models.IntegerField(max_length=5, null=True)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.driver')),
                ('transport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.transport')),
            ],
            options={
                'verbose_name': 'Поїздка',
                'verbose_name_plural': 'Поїздки',
            },
        ),
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('liters', models.IntegerField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('timestamp', models.DateTimeField()),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.trip')),
            ],
            options={
                'verbose_name': 'Паливо',
                'verbose_name_plural': 'Палива',
            },
        ),
    ]
