# Generated by Django 5.2.8 on 2025-12-18 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('FIZ', 'Фізичне лице'), ('FOP', 'ФОП'), ('COMP', 'Компанія')], max_length=10)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('inn', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('erdpou', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('contact_person_first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_person_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=127, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Клієнт',
                'verbose_name_plural': 'Клієнти',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='padlo')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('license', models.CharField(blank=True, max_length=100, null=True)),
                ('inn', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('experience', models.TextField(max_length=500)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('status', models.CharField(choices=[('F', 'Вільний'), ('OW', 'В дорозі')], default='F', max_length=20)),
            ],
            options={
                'verbose_name': 'Водій',
                'verbose_name_plural': 'Водії',
                'ordering': ('last_name',),
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_model', models.CharField(blank=True, max_length=40, null=True)),
                ('license_plate', models.CharField(blank=True, max_length=10, null=True)),
                ('fuel_rate', models.IntegerField(blank=True, default=0, null=True)),
                ('vin', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('mileage', models.SmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('F', 'Вільний'), ('OW', 'В дорозі')], default='F', max_length=20)),
                ('to', models.CharField(choices=[('NS', 'Потрібне ТО'), ('S', 'Обслужений'), ('OS', 'На обслуговувані'), ('R', 'В ремонті')], default='S', max_length=20)),
                ('miles_to_inspect', models.SmallIntegerField(blank=True, null=True)),
                ('next_inspect', models.SmallIntegerField(blank=True, default=models.SmallIntegerField(blank=True, null=True), null=True)),
            ],
            options={
                'verbose_name': 'Транспорт',
                'verbose_name_plural': 'Транспорти',
                'ordering': ('transport_model',),
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('S', 'ТО'), ('R', 'Ремонт')], max_length=15)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('date', models.DateField()),
                ('transport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.transport')),
            ],
            options={
                'verbose_name': 'Технічне обслуговування',
                'verbose_name_plural': 'Технічні обслуговування',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.CharField(blank=True, max_length=20, null=True)),
                ('end_point', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('P', 'Виконується'), ('C', 'Виконано')], default='P', max_length=20)),
                ('distance', models.IntegerField(blank=True, null=True)),
                ('fuel_status', models.CharField(choices=[('O', 'Надвитрата'), ('N', 'Норма')], default='N', max_length=20)),
                ('fuel_actual', models.IntegerField(blank=True, null=True)),
                ('fuel_planned', models.IntegerField(blank=True, null=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.driver')),
                ('transport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.transport')),
            ],
            options={
                'verbose_name': 'Поїздка',
                'verbose_name_plural': 'Поїздки',
            },
        ),
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liters', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('timestamp', models.DateTimeField()),
                ('transport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.transport')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.trip')),
            ],
            options={
                'verbose_name': 'Паливо',
                'verbose_name_plural': 'Палива',
            },
        ),
    ]
