# Generated by Django 5.2.8 on 2025-12-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contact_person_first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contact_person_last_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='inn',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='inn',
        ),
        migrations.AddField(
            model_name='client',
            name='ipn',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Ідентифікаційний код'),
        ),
        migrations.AddField(
            model_name='driver',
            name='ipn',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Ідентифікаційний код'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('FIZ', 'Фізичне лице'), ('FOP', 'ФОП'), ('COMP', 'Компанія')], max_length=10, verbose_name='Тип клієнта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва компанії'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=127, null=True, verbose_name='Електронна пошта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='erdpou',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='ЄРДПОУ'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, default='+380', max_length=13, null=True, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='experience',
            field=models.TextField(max_length=500, verbose_name='Досвід роботи. Про себе'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='driver',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Посвідчення водія'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(blank=True, default='+380', max_length=13, null=True, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('F', 'Вільний'), ('OW', 'В дорозі')], default='F', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='fuellog',
            name='liters',
            field=models.IntegerField(blank=True, null=True, verbose_name='Літри'),
        ),
        migrations.AlterField(
            model_name='fuellog',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='fuellog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата заправки'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='type',
            field=models.CharField(choices=[('S', 'ТО'), ('R', 'Ремонт')], max_length=15, verbose_name='Тип обслуговування'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='fuel_rate',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Рівень палива'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='license_plate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номера'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='mileage',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Пробіг'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='miles_to_inspect',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='ТО раз в'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='next_inspect',
            field=models.SmallIntegerField(blank=True, default=models.SmallIntegerField(blank=True, null=True, verbose_name='ТО раз в'), null=True, verbose_name='Наступне ТО'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='status',
            field=models.CharField(choices=[('F', 'Вільний'), ('OW', 'В дорозі')], default='F', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='to',
            field=models.CharField(choices=[('NS', 'Потрібне ТО'), ('S', 'Обслужений'), ('OS', 'На обслуговувані'), ('R', 'В ремонті')], default='S', max_length=20, verbose_name='Технічне обслуговування'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='transport_model',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='VIN-номер'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='distance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Відстань'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_point',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Кінець'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='fuel_actual',
            field=models.IntegerField(blank=True, null=True, verbose_name="Реальний об'єм палива"),
        ),
        migrations.AlterField(
            model_name='trip',
            name='fuel_planned',
            field=models.IntegerField(blank=True, null=True, verbose_name="Запланований об'єм палива"),
        ),
        migrations.AlterField(
            model_name='trip',
            name='fuel_status',
            field=models.CharField(choices=[('O', 'Надвитрата'), ('N', 'Норма')], default='N', max_length=20, verbose_name='Статус пального'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_point',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Старт'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('P', 'Виконується'), ('C', 'Виконано')], default='P', max_length=20, verbose_name='Статус'),
        ),
    ]
