# Generated by Django 6.0.4 on 2026-04-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='mileage',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Пробіг'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='miles_to_inspect',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ТО раз в'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='next_inspect',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Наступне ТО'),
        ),
    ]
