# Generated by Django 5.2.8 on 2025-11-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuellog',
            name='liters',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transport',
            name='fuel_rate',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='transport',
            name='mileage',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='distance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='fuel_planned',
            field=models.IntegerField(null=True),
        ),
    ]
