# Generated by Django 5.2.8 on 2025-12-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_client_contact_person_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='erdpou',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='ЄРДПОУ'),
        ),
    ]
