# Generated by Django 5.2.8 on 2025-12-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_driver_id_alter_fuellog_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='itn',
            field=models.CharField(default='0000000000', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='vin',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
