# Generated by Django 5.2.8 on 2025-12-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_driver_itn_alter_transport_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='itn',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
