# Generated by Django 5.2.8 on 2025-12-04 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_driver_itn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ('last_name',), 'verbose_name': 'Водій', 'verbose_name_plural': 'Водії'},
        ),
        migrations.AlterModelOptions(
            name='transport',
            options={'ordering': ('transport_model',), 'verbose_name': 'Транспорт', 'verbose_name_plural': 'Транспорти'},
        ),
    ]
