# Generated by Django 5.2.8 on 2026-02-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_client_created_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.FileField(default=1, upload_to='./payments', verbose_name='Платіжка'),
            preserve_default=False,
        ),
    ]
