# Generated by Django 5.2.8 on 2025-12-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_driver_options_alter_transport_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.CharField(default='В рейсі', max_length=15),
        ),
    ]
