# Generated by Django 5.2.8 on 2026-02-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.FileField(blank=True, null=True, upload_to='./payments', verbose_name='Платіжка'),
        ),
    ]
