# Generated by Django 5.2.8 on 2026-02-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Дата створення'),
        ),
    ]
