# Generated by Django 5.2.8 on 2025-12-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_driver_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='itn',
            field=models.CharField(max_length=10),
        ),
    ]
