# Generated by Django 5.2.8 on 2026-02-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created',
            field=models.DateField(auto_now=True, verbose_name='Дата створення'),
        ),
    ]
