# Generated by Django 5.2.8 on 2026-02-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_client_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.FileField(blank=True, null=True, upload_to='./payments/', verbose_name='Платіжка'),
        ),
    ]
