# Generated by Django 5.2.8 on 2025-12-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_transport_miles_to_inspect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='miles_to_inspect',
            field=models.SmallIntegerField(),
        ),
    ]
