# Generated by Django 5.2.8 on 2025-12-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_transport_miles_to_inspect'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='next_inspect',
            field=models.SmallIntegerField(default=0),
        ),
    ]
