# Generated by Django 5.2.8 on 2025-12-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_transport_next_inspect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='next_inspect',
            field=models.SmallIntegerField(),
        ),
    ]
