# Generated by Django 5.2.8 on 2026-02-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('NP', 'Не оплачено'), ('P', 'Оплачено')], default='Не оплачено', null=True, verbose_name='Статус оплати'),
        ),
    ]
