# Generated by Django 5.2.8 on 2026-02-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('NP', 'Не оплачено'), ('P', 'Оплачено')], default='NP', null=True, verbose_name='Статус оплати'),
        ),
    ]
