# Generated by Django 5.2.8 on 2025-12-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_transport_next_inspect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='next_inspect',
            field=models.SmallIntegerField(default=models.SmallIntegerField()),
        ),
    ]
