# Generated by Django 5.2.8 on 2025-12-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_transport_next_inspect'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='to',
            field=models.CharField(choices=[('NS', 'Need to service'), ('S', 'Served')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(max_length=15),
        ),
    ]
