# Generated by Django 5.2.8 on 2026-02-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='fuel_actual',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name="Реальний об'єм палива"),
        ),
        migrations.AlterField(
            model_name='trip',
            name='fuel_planned',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name="Запланований об'єм палива"),
        ),
    ]
