# Generated by Django 5.2.8 on 2026-02-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_trip_fuel_actual_alter_trip_fuel_planned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='type',
            field=models.CharField(choices=[('S', 'ТО'), ('R', 'Ремонт'), ('E', 'Завершено')], max_length=15, verbose_name='Тип обслуговування'),
        ),
    ]
