# Generated by Django 5.2.8 on 2025-12-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_transport_to_alter_driver_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('F', 'Free'), ('OW', 'On the way')], default='F', max_length=20),
        ),
        migrations.AlterField(
            model_name='transport',
            name='status',
            field=models.CharField(choices=[('F', 'Free'), ('OW', 'On the way')], default='F', max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('P', 'Performing'), ('C', 'Completed')], default='P', max_length=20),
        ),
    ]
