# Generated by Django 5.2.8 on 2025-12-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_driver_status_alter_transport_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='fuel_status',
            field=models.CharField(choices=[('O', 'Overspending'), ('N', 'Normal')], default='N', max_length=20),
        ),
    ]
