# Generated by Django 5.2.8 on 2026-02-15 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_maintenance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='order_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.order'),
            preserve_default=False,
        ),
    ]
