# Generated by Django 5.2.8 on 2025-12-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_trip_fuel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='fuel_actual',
            field=models.IntegerField(default=0),
        ),
    ]
