# Generated by Django 5.2.8 on 2026-02-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_trip_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='photo',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
    ]
