# Generated by Django 5.2.8 on 2026-02-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_transport_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='photo',
            field=models.ImageField(upload_to='images/', verbose_name='Фото'),
        ),
    ]
