# Generated by Django 5.2.8 on 2026-02-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_transport_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='photo',
            field=models.ImageField(default=0, upload_to='photos/', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
