# Generated by Django 5.2.8 on 2025-12-10 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_fuellog_transport_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuellog',
            name='transport_id',
        ),
    ]
