# Generated by Django 5.2.8 on 2025-12-10 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_fuellog_transport_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuellog',
            name='transport_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.transport'),
        ),
    ]
