# Generated by Django 5.2.8 on 2026-02-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_driver_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Адреса доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('NP', 'Не оплачено'), ('P', 'Оплачено')], default='NP', max_length=40, null=True, verbose_name='Статус оплати'),
        ),
    ]
