# Generated by Django 5.2.8 on 2026-02-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_order_address_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
