# Generated by Django 5.2.8 on 2025-12-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_fuellog_transport_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='fuel_rate',
            field=models.IntegerField(default=0),
        ),
    ]
