# Generated by Django 5.2.8 on 2026-02-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_order_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
