# Generated by Django 5.2.8 on 2025-12-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_transport_fuel_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='fuel_actual',
            field=models.IntegerField(),
        ),
    ]
