# Generated by Django 5.2.8 on 2026-02-22 14:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_order_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
