# Generated by Django 5.2.8 on 2026-02-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_order_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_register', models.FileField(blank=True, null=True, upload_to='payments/', verbose_name='Реєстр оплат')),
            ],
            options={
                'verbose_name': ('Оплата',),
                'verbose_name_plural': 'Оплати',
            },
        ),
    ]
