# Generated by Django 5.2.8 on 2026-02-22 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_order_payment_payment_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order_id',
        ),
    ]
