# Generated by Django 5.2.8 on 2026-02-23 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_payment_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
