# Generated by Django 5.2.8 on 2026-02-25 12:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('payment_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('company', models.CharField(blank=True, null=True, verbose_name='Компанія')),
                ('name', models.CharField(blank=True, null=True, verbose_name='ПІБ/Представник')),
                ('ipn', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Ідентифікаційни код')),
                ('edrpou', models.IntegerField(blank=True, null=True, unique=True, verbose_name='ЄДРПОУ')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='Сума')),
            ],
            options={
                'verbose_name': 'Чернетка оплати',
                'verbose_name_plural': 'Чернетка оплат',
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('client_id',), 'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='erdpou',
        ),
        migrations.AddField(
            model_name='client',
            name='edrpou',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='ЄДРПОУ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.payment'),
        ),
    ]
