# Generated by Django 5.2.8 on 2026-02-25 12:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_payment_alter_order_options_remove_client_erdpou_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
