# Generated by Django 5.2.8 on 2026-02-25 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_order_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
    ]
