# Generated by Django 5.2.8 on 2026-02-25 12:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_order_payment_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
