# Generated by Django 5.2.8 on 2026-02-25 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_delete_payment_order_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='edrpou',
            new_name='erdpou',
        ),
    ]
