# Generated by Django 5.2.8 on 2026-02-25 12:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_rename_edrpou_client_erdpou'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('payment_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('company', models.CharField(blank=True, null=True, verbose_name='Компанія')),
                ('name', models.CharField(blank=True, null=True, verbose_name='ПІБ/Представник')),
                ('ipn', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Ідентифікаційни код')),
                ('edrpou', models.IntegerField(blank=True, null=True, unique=True, verbose_name='ЄДРПОУ')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='Сума')),
            ],
            options={
                'verbose_name': 'Чернетка оплати',
                'verbose_name_plural': 'Чернетка оплат',
            },
        ),
        migrations.RenameField(
            model_name='client',
            old_name='erdpou',
            new_name='edrpou',
        ),
    ]
