# Generated by Django 5.2.8 on 2026-02-25 12:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_payment_rename_erdpou_client_edrpou'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='edrpou',
            field=models.CharField(blank=True, null=True, verbose_name='ЄДРПОУ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ipn',
            field=models.CharField(blank=True, null=True, verbose_name='Ідентифікаційни код'),
        ),
    ]
