# Generated by Django 5.2.8 on 2026-02-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_remove_payment_payment_id_alter_order_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.CharField(blank=True, null=True, verbose_name='Дата'),
        ),
    ]
