# Generated by Django 5.2.8 on 2026-02-25 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
    ]
