# Generated by Django 5.2.8 on 2026-02-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_order_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_id',
            new_name='pay_id',
        ),
    ]
