# Generated by Django 5.2.8 on 2026-02-26 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_rename_payment_id_order_pay_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='id',
            new_name='payment_id',
        ),
    ]
