# Generated by Django 5.2.8 on 2026-02-26 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_rename_id_payment_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_id',
            new_name='id',
        ),
    ]
