# Generated by Django 5.2.8 on 2026-02-28 14:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_rename_payment_id_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayedOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('date', models.CharField(blank=True, null=True, verbose_name='Дата')),
                ('company', models.CharField(blank=True, null=True, verbose_name='Компанія')),
                ('name', models.CharField(blank=True, null=True, verbose_name='ПІБ/Представник')),
                ('ipn', models.CharField(blank=True, null=True, verbose_name='Ідентифікаційни код')),
                ('edrpou', models.CharField(blank=True, null=True, verbose_name='ЄДРПОУ')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='Сума')),
            ],
            options={
                'verbose_name': 'Оплачене замовлення',
                'verbose_name_plural': 'Оплачені замовлення',
            },
        ),
        migrations.RenameModel(
            old_name='Payment',
            new_name='NoPayedOrder',
        ),
        migrations.AlterModelOptions(
            name='nopayedorder',
            options={'verbose_name': 'Оплачене замовлення', 'verbose_name_plural': 'Оплачені замовлення'},
        ),
    ]
