# Generated by Django 5.2.8 on 2026-03-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_payedorder_rename_payment_nopayedorder_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayedOrder',
        ),
        migrations.AlterModelOptions(
            name='nopayedorder',
            options={'verbose_name': 'Не оплачене замовлення', 'verbose_name_plural': 'Не оплачені замовлення'},
        ),
        migrations.AlterField(
            model_name='nopayedorder',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Айді оплати'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Айді оплати'),
        ),
    ]
