# Generated by Django 5.2.8 on 2026-03-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_delete_payedorder_alter_nopayedorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nopayedorder',
            name='pay_id',
            field=models.CharField(default=1, max_length=10, unique=True, verbose_name='Айді оплати'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nopayedorder',
            name='edrpou',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='ЄДРПОУ'),
        ),
        migrations.AlterField(
            model_name='nopayedorder',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nopayedorder',
            name='ipn',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Ідентифікаційни код'),
        ),
    ]
