# Generated by Django 5.2.8 on 2026-03-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_nopayedorder_pay_id_alter_nopayedorder_edrpou_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='next_inspect',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Наступне ТО'),
        ),
    ]
