# Generated by Django 5.2.8 on 2026-03-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_transport_next_inspect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end_point',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Кінець'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_point',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Старт'),
        ),
    ]
