# Generated by Django 5.2.8 on 2026-03-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_trip_end_point_alter_trip_start_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuellog',
            name='liters',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Літри'),
        ),
        migrations.AlterField(
            model_name='fuellog',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='nopayedorder',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Сума'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='mileage',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Пробіг'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='miles_to_inspect',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='ТО раз в'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='distance',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Відстань'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('AC', 'Очікує підтвердження'), ('P', 'Виконується'), ('C', 'Виконано')], default='P', max_length=20, verbose_name='Статус'),
        ),
    ]
