# Generated by Django 5.2.8 on 2026-03-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_fuellog_liters_alter_fuellog_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('AC', 'Очікує підтвердження'), ('P', 'Виконується'), ('C', 'Виконано')], default='AC', max_length=20, verbose_name='Статус'),
        ),
    ]
