# Generated by Django 5.2.8 on 2026-03-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('W', 'Очікує'), ('D', 'Доставляється'), ('E', 'Доставлено')], default='W', null=True, verbose_name='Статус доставки'),
        ),
    ]
