# Generated by Django 5.2.8 on 2026-03-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='experience',
            field=models.TextField(max_length=500, null=True, verbose_name='Досвід роботи. Про себе'),
        ),
    ]
