# Generated by Django 5.2.8 on 2026-03-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_alter_driver_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='fuel_rate',
            field=models.IntegerField(blank=True, default=0, verbose_name='Рівень палива'),
        ),
    ]
