# Generated by Django 5.2.8 on 2026-03-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_alter_transport_fuel_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nopayedorder',
            name='pay_id',
            field=models.IntegerField(max_length=10, unique=True, verbose_name='Айді оплати'),
        ),
    ]
