# Generated by Django 5.2.8 on 2026-03-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_alter_nopayedorder_pay_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nopayedorder',
            name='pay_id',
            field=models.IntegerField(unique=True, verbose_name='Айді оплати'),
        ),
    ]
