# Generated by Django 5.2.8 on 2026-03-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_alter_nopayedorder_pay_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Айді оплати'),
        ),
    ]
