# Generated by Django 5.2.8 on 2026-03-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_alter_order_pay_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nopayedorder',
            name='id',
        ),
        migrations.AlterField(
            model_name='nopayedorder',
            name='pay_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Айді оплати'),
        ),
    ]
