# Generated by Django 5.2.8 on 2026-03-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_remove_nopayedorder_id_alter_nopayedorder_pay_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('F', 'Вільний'), ('OW', 'В дорозі'), ('W', 'Вихідний')], default='F', max_length=20, verbose_name='Статус'),
        ),
    ]
