# Generated by Django 5.2.8 on 2026-03-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_alter_driver_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='weekend_until',
            field=models.DateField(blank=True, null=True, verbose_name='Вихідний до'),
        ),
    ]
