# Generated by Django 5.2.8 on 2026-04-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_driver_weekend_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuellog',
            name='liters',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Літри'),
        ),
        migrations.AlterField(
            model_name='nopayedorder',
            name='total',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Сума'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='fuel_rate',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Рівень палива'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Пробіг'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='miles_to_inspect',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='ТО раз в'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='next_inspect',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Наступне ТО'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='distance',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Відстань'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='fuel_actual',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Реальний об'єм палива"),
        ),
        migrations.AlterField(
            model_name='trip',
            name='fuel_planned',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Запланований об'єм палива"),
        ),
    ]
