# Generated by Django 5.2.8 on 2026-04-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_alter_fuellog_liters_alter_nopayedorder_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='experience',
            new_name='about',
        ),
        migrations.AlterField(
            model_name='driver',
            name='license',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Посвідчення водія'),
        ),
    ]
