# Generated by Django 5.2.8 on 2026-04-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_rename_experience_driver_about_alter_driver_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(blank=True, default='+380', max_length=13, null=True, unique=True, verbose_name='Номер телефону'),
        ),
    ]
