# Generated by Django 5.2.8 on 2026-04-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_alter_driver_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(blank=True, default='+38', max_length=13, null=True, unique=True, verbose_name='Номер телефону'),
        ),
    ]
